# Harmony Jekyll theme general configurations

# Base URL
# baseurl: /

# Site live URL
# url: blog.youdaxue.com

# Localhost
#url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: 优达学城（Udacity）| 官方博客
  # Little description about your site
  description: > #
   优达学城（Udacity）官方资讯和技术分享，掌握全球最前沿技术
  keywords: >
    优达学城,机器学习,数据分析,iOS开发,Android开发,安卓开发,编程教程,技术教程,公开课,在线课程,Udacity,MOOC，博客
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Udacity China
    email: info@youdaxue.com
    url: https://cn.udacity.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social:
    github: udacity
    twitter: udacity
    facebook:
    gplus:
    dribble:
    pinterest:
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
